import { GoogleGenAI } from '@google/genai';

export async function generateConfidenceScore(apiKey: string, contextData: any) {
  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
RÔLE : Tu es un coach running de haut niveau, expert en physiologie du sport.
Tu analyses l'évolution chronologique d'un "macrocycle" d'entraînement (semaine par semaine) pour identifier la vraie dynamique de charge, l'affûtage (tapering), et l'assimilation. Tu ne fais pas que de simples moyennes.

OBJECTIF DE L'ATHLÈTE :
Événement : ${contextData.eventName} (${contextData.distance}m) dans ${contextData.weeksToEvent} semaines.
Chrono cible : ${Math.floor(contextData.targetTime / 60)} minutes.

PROFIL DE L'ATHLÈTE :
Âge: ${contextData.age}, Sexe: ${contextData.sex}, Poids: ${contextData.weight}kg
FC repos: ${contextData.restingHR} bpm, FC max: ${contextData.maxHR} bpm

MACROCYCLE D'ENTRAÎNEMENT (12 dernières semaines, chronologique) :
(S-0 = cette semaine, S-11 = il y a 11 semaines. Eff(Z2) = Efficience aérobie m/battement (PLUS HAUT EST MIEUX). Ratio = % de temps passé en Endurance Fondamentale (Z1/Z2) vs Haute Intensité (Z3+)).

${contextData.macrocycleSummary}

CONSIGNES :
1. Analyse la dynamique semaine après semaine (volume progressif ? sortie longue adéquate par rapport à la distance cible ? amélioration de l'efficience ?).
2. Donne un SCORE DE CONFIANCE (0-100) fondé sur cette évolution et le temps restant avant la course.
3. Liste les POINTS FORTS (max 3) avec des données chiffrées issues de la progression hebdomadaire (ex: "Le volume a cru de X à Y, l'efficience a grimpé...").
4. Liste les FAIBLESSES (max 3) avec des données chiffrées et une approche coach (ex: "La sortie longue stagne à X km depuis 3 semaines").
5. Donne des ACTIONS CONCRÈTES (max 3) calibrées selon les semaines restantes (Tapering ou Surcharge).

RÉPOND UNIQUEMENT AVEC CE FORMAT JSON EXACT :
{
  "score": 65,
  "summary": "Résumé cash en une phrase.",
  "strengths": ["Point fort 1", "Point fort 2"],
  "weaknesses": ["Faiblesse 1", "Faiblesse 2"],
  "actions": ["Action 1", "Action 2"]
}
`;

  const response = await ai.models.generateContent({
    model: 'gemini-3.6-flash',
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
    }
  });

  if (!response.text) {
    throw new Error('No text generated by Gemini');
  }

  return JSON.parse(response.text);
}
