import { GoogleGenAI } from '@google/genai';

export async function generateConfidenceScore(apiKey: string, contextData: any) {
  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
RÔLE : Tu es un coach running expert, analytique et sans complaisance.
Tu ne cherches pas à faire plaisir. Tu dis la vérité sur les chances d'atteinte de l'objectif.

OBJECTIF DE L'ATHLÈTE :
${contextData.eventName} le ${contextData.eventDate} en moins de ${contextData.targetTime / 60} minutes
Distance : ${contextData.distance}m

PROFIL DE L'ATHLÈTE :
Âge: ${contextData.age}, Sexe: ${contextData.sex}, Poids: ${contextData.weight}kg
FC repos: ${contextData.restingHR} bpm, FC max: ${contextData.maxHR} bpm

DONNÉES D'ENTRAÎNEMENT RÉCENTES :
- Volume total récent : ${contextData.totalKm} km
- Efficience aérobie (pace/FC) : ${contextData.aerobicEfficiency}
- Cadence moyenne au seuil : ${contextData.thresholdCadence} SPM
- Temps en zones (secondes) : Z1=${contextData.timeInZone1}, Z2=${contextData.timeInZone2}, Z3=${contextData.timeInZone3}, Z4=${contextData.timeInZone4}, Z5=${contextData.timeInZone5}

CONSIGNES :
1. Donne un SCORE DE CONFIANCE de 0 à 100 sur l'atteinte de l'objectif.
2. Liste les POINTS FORTS (max 3) avec données chiffrées à l'appui.
3. Liste les FAIBLESSES (max 3) avec données chiffrées à l'appui — sois cash.
4. Donne des ACTIONS CONCRÈTES (max 3) pour augmenter le score.

RÉPOND UNIQUEMENT AVEC CE FORMAT JSON EXACT, SANS BACKTICKS, SANS TEXTE AVANT NI APRÈS :
{
  "score": 65,
  "summary": "Résumé cash en une phrase.",
  "strengths": ["Point fort 1", "Point fort 2"],
  "weaknesses": ["Faiblesse 1", "Faiblesse 2"],
  "actions": ["Action 1", "Action 2"]
}
`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
    }
  });

  if (!response.text) {
    throw new Error('No text generated by Gemini');
  }

  return JSON.parse(response.text);
}
